### PR TITLE
settings: fix for default web browser

### PR DESCRIPTION
**Pull request by sergio-costas**
This patch complements https://github.com/canonical/ubuntu-core-desktop-snapd/pull/16 to allow to set the default web browser in core desktop.

### CODE REVIEW

**Review by jhenstridge — CHANGES_REQUESTED** [review]
I think we probably want to remove the rest of the changes in `hooks/500-create-xdg.chroot`:

* We don't want the xdg-open proxy: having it called by `snap userd` will cause an infinite loop.
* Similarly, we don't want `xdg-open.desktop`, since it could cause the xdg-utils version of xdg-open to cause an infinite loop.
* We don't need the `mimeapps.list` file, since it only references `xdg-open.desktop`.

Other than that, this looks like the right direction.

**Comment by sergio-costas** [comment]
Removed. Building it to test it right now...

**Comment by sergio-costas** [comment]
Done.

**Review by kenvandine — APPROVED** [review]
Thanks!

**Pull request merged**
