### PR TITLE
Adapt to snapped pipewire

### PR DESCRIPTION
**Pull request by sergio-costas**
This PR removes pipewire and leaves it ready to use the snapped version.

### CODE REVIEW

**Review by robert-ancell — APPROVED** [review]
Change looks good to me but @jhenstridge will know best on this one.

**Comment by robert-ancell** [comment]
@sergio-costas needs merging.

**Comment by sergio-costas** [comment]
I'm not sure if we should merge this yet. I uploaded pipewire.snap to the store, but it requires manual approve because of the requested slots. I cancelled the manual approve https://dashboard.snapcraft.io/snaps/pipewire/revisions/6/

We should discuss how to proceed with this.

**Comment by sergio-costas** [comment]
Ok, I requested the slots for pipewire https://forum.snapcraft.io/t/request-for-audio-related-snap-declarations-for-pipewire-snap/42178

**Pull request merged**
